<a href="https://colab.research.google.com/github/donna6355/study_python/blob/master/senior/data_pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd

df = pd.read_csv('blogs.csv')
df

,Unnamed: 0,title,contents,date
0,0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",​ 실버일자리란 무엇인가?실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할...,2026. 2. 24. 15:46
1,1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 2~3시간이면 충분해! '등·하원 도우미' 스마트폰만 있으면 취업 끝! '데이...,2026. 2. 20. 18:22
2,2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,"최고의 연금, '주택연금' 활용하기""자식에게 집 한 채는 물려줘야지""라는 생각보다,...",2026. 3. 4. 8:05
3,3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결?노후 차량 장기렌트가 정답인 이유1. 은퇴 세대가 ...,2026. 2. 12. 15:44
4,4,은퇴 준비.노후 자금 운용설계,https://youtu.be/ehrmWJdwFNY?si=iLEzhc5BV-enca...,2026. 1. 24. 20:23
...,...,...,...,...
498,498,잘 넘어지는 사람이 치매에 걸리기 쉽다#건강체조#웃음치료#인지근력운동#건강박수#치매...,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 18. 22:05
499,499,고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보험 선택 가이드,고객 생애 주기와 보험 설계 고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보...,2025. 1. 20. 21:40
500,500,경북 영주 시니어 부업 평생 쌓아온 솜씨와 기술 활용으로 경제 활동을 독려해요,시니어의 장점만 살려 경제 활동을 독려면밀하게 검수 후 엄선된 제품 취급문의번호05...,2025. 1. 21. 14:00
501,501,#건강체조#웃음운동#치매예방체조#건강박수#자원봉사#거창사랑데이케어센터,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 10. 22:37
502,502,사주팔자는 출생의 비밀코드인가?,NaN,2025. 2. 7. 18:53

In [16]:
# df = df.rename(columns={'content': 'contents'})
# df

,Unnamed: 0,title,contents,date,nickName
0,4037,NaN,2025년엔 우리 회원님 들 ! 꽃길만 걸어요!\n\n우리 회원님 들!\n희망찬 2...,2025-01-01 00:36,의봉
1,4038,NaN,첫날 피칭 둘째날 트래킹 세째날 먹방과 쉼\n저의 일반적 차박 방식 입니다.,2025-01-01 05:20,아리수나그네
2,4039,NaN,새해 아침입니다.\n우리 회원 님들께 더 큰 행복이 임하고 더욱 건강하시기를 기원합...,2025-01-01 06:51,제이
3,4040,NaN,스마일쩡 님 반갑습니다.\n환영합니다.\n함께 즐거운 모임으로 가꾸어 나가요!,2025-01-01 06:57,제이
4,4041,첫 가입인사,안녕하세요? 좀 더 풍요롭고 따뜻한 마음을 나누고 느끼는 한해가 되었음해서 가입...,2025-01-01 07:00,스마일쩡
...,...,...,...,...,...
10754,14791,NaN,2026년 3월 4일 모임 결산\n\n(중앙박물관 + 종로 ABC)\n\n모임에 참...,2026-03-05 07:41,FREEMAN
10755,14792,NaN,'아름다운 인생' 참 듣기 좋은 말이네요.\n모든 회원님들 행복한 날들 보내시기 바...,2026-03-05 08:07,미리내99
10756,14793,NaN,안녕하세요 \n가입인사 드립니다,2026-03-05 08:43,바다놀이
10757,14794,"사교댄스, 스포츠댄스모임 26년 2회 정기모임","\n사교댄스, 스포츠댄스 \nK국사스 모임\n정기모임 26년 2회 \n총 52회 모...",2026-03-05 09:08,K국사스모임회장
10758,14795,NaN,"분명 가입인사한거 같았는데, 보니까 작성한글이 없네요. 올해가 정년퇴직이라 노후준...",2026-03-05 11:05,더늦은출발

In [36]:
df = df.dropna(subset=['contents'])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 387 entries, 0 to 501
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     387 non-null    object
 1   contents  387 non-null    object
 2   date      387 non-null    object
dtypes: object(3)
memory usage: 12.1+ KB

,title,contents,date
0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",​ 실버일자리란 무엇인가?실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할...,2026. 2. 24. 15:46
1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 2~3시간이면 충분해! '등·하원 도우미' 스마트폰만 있으면 취업 끝! '데이...,2026. 2. 20. 18:22
2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,"최고의 연금, '주택연금' 활용하기""자식에게 집 한 채는 물려줘야지""라는 생각보다,...",2026. 3. 4. 8:05
3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결?노후 차량 장기렌트가 정답인 이유1. 은퇴 세대가 ...,2026. 2. 12. 15:44
4,은퇴 준비.노후 자금 운용설계,https://youtu.be/ehrmWJdwFNY?si=iLEzhc5BV-enca...,2026. 1. 24. 20:23

In [33]:
del df['Unnamed: 0']
df

,title,contents,date
0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",​ 실버일자리란 무엇인가?실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할...,2026. 2. 24. 15:46
1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 2~3시간이면 충분해! '등·하원 도우미' 스마트폰만 있으면 취업 끝! '데이...,2026. 2. 20. 18:22
2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,"최고의 연금, '주택연금' 활용하기""자식에게 집 한 채는 물려줘야지""라는 생각보다,...",2026. 3. 4. 8:05
3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결?노후 차량 장기렌트가 정답인 이유1. 은퇴 세대가 ...,2026. 2. 12. 15:44
4,은퇴 준비.노후 자금 운용설계,https://youtu.be/ehrmWJdwFNY?si=iLEzhc5BV-enca...,2026. 1. 24. 20:23
...,...,...,...
498,잘 넘어지는 사람이 치매에 걸리기 쉽다#건강체조#웃음치료#인지근력운동#건강박수#치매...,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 18. 22:05
499,고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보험 선택 가이드,고객 생애 주기와 보험 설계 고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보...,2025. 1. 20. 21:40
500,경북 영주 시니어 부업 평생 쌓아온 솜씨와 기술 활용으로 경제 활동을 독려해요,시니어의 장점만 살려 경제 활동을 독려면밀하게 검수 후 엄선된 제품 취급문의번호05...,2025. 1. 21. 14:00
501,#건강체조#웃음운동#치매예방체조#건강박수#자원봉사#거창사랑데이케어센터,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 10. 22:37
502,사주팔자는 출생의 비밀코드인가?,NaN,2025. 2. 7. 18:53

In [37]:
import re

remove = re.compile(r'[^가-힣]')
df['contents'] = df['contents'].apply(lambda x : remove.sub(" ",x))
df['contents'] = df['contents'].apply(lambda x : x.replace("  "," "))
df['contents'] = df['contents'].apply(lambda x : x.replace("\n",""))
df

/tmp/ipykernel_403/28295354.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['contents'] = df['contents'].apply(lambda x : remove.sub(" ",x))
/tmp/ipykernel_403/28295354.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['contents'] = df['contents'].apply(lambda x : x.replace("  "," "))
/tmp/ipykernel_403/28295354.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['contents'] = df['contents'].apply(lambda x : x.replace("\n",""))

,title,contents,date
0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",실버일자리란 무엇인가 실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할 ...,2026. 2. 24. 15:46
1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 시간이면 충분해 등 하원 도우미 스마트폰만 있으면 취업 끝 데이터 수집가...,2026. 2. 20. 18:22
2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,최고의 연금 주택연금 활용하기 자식에게 집 한 채는 물려줘야지 라는 생각보다 내 ...,2026. 3. 4. 8:05
3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결 노후 차량 장기렌트가 정답인 이유 은퇴 세대가 반...,2026. 2. 12. 15:44
4,은퇴 준비.노후 자금 운용설계,,2026. 1. 24. 20:23
...,...,...,...
497,노인 평생교육에 대해 알아보자!,고령화의 심화와 노인 평생교육의 필요성노인 평생교육의 역할 국내 노인 평생교육 사례...,2025. 1. 1. 14:00
498,잘 넘어지는 사람이 치매에 걸리기 쉽다#건강체조#웃음치료#인지근력운동#건강박수#치매...,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 18. 22:05
499,고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보험 선택 가이드,고객 생애 주기와 보험 설계 고객 생애 주기와 보험 설계 인생 단계별 최적의 보험...,2025. 1. 20. 21:40
500,경북 영주 시니어 부업 평생 쌓아온 솜씨와 기술 활용으로 경제 활동을 독려해요,시니어의 장점만 살려 경제 활동을 독려면밀하게 검수 후 엄선된 제품 취급문의번호 ...,2025. 1. 21. 14:00
501,#건강체조#웃음운동#치매예방체조#건강박수#자원봉사#거창사랑데이케어센터,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 10. 22:37

In [19]:
#가입인사 제거, 가입, 반갑
df = df[~df['contents'].str.contains(r'반갑|가입', na=False, regex=True)]
df

,title,contents,date,nickName
0,NaN,년엔 우리 회원님 들 ! 꽃길만 걸어요!우리 회원님 들!희망찬 년을 맞이하기...,2025-01-01 00:36,의봉
1,NaN,첫날 피칭 둘째날 트래킹 세째날 먹방과 쉼저의 일반적 차박 방식 입니다.,2025-01-01 05:20,아리수나그네
2,NaN,새해 아침입니다.우리 회원 님들께 더 큰 행복이 임하고 더욱 건강하시기를 기원합니다...,2025-01-01 06:51,제이
5,NaN,년 월 일 수 입니다. 새해 을사년 에는 뜻하신 모든일이 이루워지시길 기원합니다...,2025-01-01 07:04,skyspace
6,NaN,부산 청사포 일출. 새해복 많이 받으세요!,2025-01-01 08:54,하나두리
...,...,...,...,...
10750,NaN,눈 오는날 올렸던매화 이제 만개했어요 하우스에서 찍은사진을배경색과 받침대를 제미나이...,2026-03-04 15:12,장영권
10751,NaN,안녕하세요반가워요,2026-03-04 16:01,잠실
10752,등업인사,잘부탁드합니다.,2026-03-04 21:40,여준씨
10754,NaN,년 월 일 모임 결산 중앙박물관 종로 모임에 참석해 주신 분들께 감사드립니...,2026-03-05 07:41,FREEMAN
10755,NaN,아름다운 인생 참 듣기 좋은 말이네요.모든 회원님들 행복한 날들 보내시기 바랍니다,2026-03-05 08:07,미리내99

0

In [49]:

df['contents'] = df['contents'].apply(lambda x : x.strip())
df['len'] = df['contents'].apply(lambda x : len(x))
df = df.loc[df['len']>=20]
del df['len']
df = df.reset_index(drop=True)
df

,title,contents,date
0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",실버일자리란 무엇인가 실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할 수...,2026. 2. 24. 15:46
1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 시간이면 충분해 등 하원 도우미 스마트폰만 있으면 취업 끝 데이터 수집가...,2026. 2. 20. 18:22
2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,최고의 연금 주택연금 활용하기 자식에게 집 한 채는 물려줘야지 라는 생각보다 내 ...,2026. 3. 4. 8:05
3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결 노후 차량 장기렌트가 정답인 이유 은퇴 세대가 반...,2026. 2. 12. 15:44
4,과거 은퇴 세대가 꿈꾸던 노후 vs 현재 은퇴 세대가 설계하는 노후,과거 은퇴 세대가 꿈꾸던 노후 현재 은퇴 세대가 설계하는 노후 과거 은퇴 세대가 ...,2025. 12. 16. 16:25
...,...,...,...
328,노인 평생교육에 대해 알아보자!,고령화의 심화와 노인 평생교육의 필요성노인 평생교육의 역할 국내 노인 평생교육 사례...,2025. 1. 1. 14:00
329,잘 넘어지는 사람이 치매에 걸리기 쉽다#건강체조#웃음치료#인지근력운동#건강박수#치매...,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 18. 22:05
330,고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보험 선택 가이드,고객 생애 주기와 보험 설계 고객 생애 주기와 보험 설계 인생 단계별 최적의 보험...,2025. 1. 20. 21:40
331,경북 영주 시니어 부업 평생 쌓아온 솜씨와 기술 활용으로 경제 활동을 독려해요,시니어의 장점만 살려 경제 활동을 독려면밀하게 검수 후 엄선된 제품 취급문의번호,2025. 1. 21. 14:00
332,#건강체조#웃음운동#치매예방체조#건강박수#자원봉사#거창사랑데이케어센터,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 10. 22:37

In [50]:
# ## ===== konlpy 설치 ===== ##
# from google.colab import drive
# drive.mount('/content/drive')

# # 코랩 konlpy 실행
# !curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

# # Mecab 설치 후 Google Drive에 복사
# !cp -r /usr/local/lib/mecab /content/drive/MyDrive/mecab
# !cp -r /usr/local/etc/mecabrc /content/drive/MyDrive/mecab
# ## ===== konlpy 설치 ===== ##

from konlpy.tag import Okt
from tqdm import tqdm
tqdm.pandas()

okt = Okt()
def extract_pos(text, pos):
  left = []
  for t,c in okt.pos(text, stem = True, norm = True):
    if c in pos:
      left.append(t)
  return left

df["token"] = df["contents"].progress_apply(lambda x : extract_pos(x,['Noun','Adjective','Verb']))
df

100%|██████████| 333/333 [00:43<00:00,  7.57it/s]

,title,contents,date,token
0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",실버일자리란 무엇인가 실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할 수...,2026. 2. 24. 15:46,"[실버, 일자리, 란, 무엇, 실버, 일자리, 고령자, 사회, 기여, 자기, 발전,..."
1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 시간이면 충분해 등 하원 도우미 스마트폰만 있으면 취업 끝 데이터 수집가...,2026. 2. 20. 18:22,"[하루, 시간, 이면, 충분하다, 등, 하원, 도우미, 스마트폰, 있다, 취업, 끝..."
2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,최고의 연금 주택연금 활용하기 자식에게 집 한 채는 물려줘야지 라는 생각보다 내 ...,2026. 3. 4. 8:05,"[최고, 연금, 주택연금, 활용, 하다, 자식, 집, 하다, 채다, 물리다, 생각,..."
3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결 노후 차량 장기렌트가 정답인 이유 은퇴 세대가 반...,2026. 2. 12. 15:44,"[은퇴, 후, 보험료, 폭탄, 피, 비결, 노후, 차량, 장기, 렌트, 정답, 이유..."
4,과거 은퇴 세대가 꿈꾸던 노후 vs 현재 은퇴 세대가 설계하는 노후,과거 은퇴 세대가 꿈꾸던 노후 현재 은퇴 세대가 설계하는 노후 과거 은퇴 세대가 ...,2025. 12. 16. 16:25,"[과거, 은퇴, 세대, 꿈꾸다, 노후, 현재, 은퇴, 세대, 설계, 하다, 노후, ..."
...,...,...,...,...
328,노인 평생교육에 대해 알아보자!,고령화의 심화와 노인 평생교육의 필요성노인 평생교육의 역할 국내 노인 평생교육 사례...,2025. 1. 1. 14:00,"[고령화, 심화, 노인, 평생교육, 필요성, 노인, 평생교육, 역할, 국내, 노인,..."
329,잘 넘어지는 사람이 치매에 걸리기 쉽다#건강체조#웃음치료#인지근력운동#건강박수#치매...,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 18. 22:05,"[해, 주신, 신, 어렵다, 힘들다, 작다, 것, 하나, 웃다, 감사하다, 건강하다..."
330,고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보험 선택 가이드,고객 생애 주기와 보험 설계 고객 생애 주기와 보험 설계 인생 단계별 최적의 보험...,2025. 1. 20. 21:40,"[고객, 생애, 주기, 보험, 설계, 고객, 생애, 주기, 보험, 설계, 인생, 단..."
331,경북 영주 시니어 부업 평생 쌓아온 솜씨와 기술 활용으로 경제 활동을 독려해요,시니어의 장점만 살려 경제 활동을 독려면밀하게 검수 후 엄선된 제품 취급문의번호,2025. 1. 21. 14:00,"[시니어, 장점, 살리다, 경제, 활동, 독려, 면밀하다, 검수, 후, 엄선, 되다..."
332,#건강체조#웃음운동#치매예방체조#건강박수#자원봉사#거창사랑데이케어센터,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 10. 22:37,"[해, 주신, 신, 어렵다, 힘들다, 작다, 것, 하나, 웃다, 감사하다, 건강하다..."

In [22]:
# !pip install kiwipiepy
from kiwipiepy.utils import Stopwords

stopwords = Stopwords()
sw = set([i[0] for i in stopwords.stopwords])
sw

{'ᆫ',
 'ᆫ다',
 'ᆯ',
 '가',
 '같',
 '것',
 '게',
 '겠',
 '고',
 '과',
 '그',
 '기',
 '까지',
 '나',
 '년',
 '는',
 '다',
 '다고',
 '다는',
 '대하',
 '더',
 '던',
 '도',
 '되',
 '들',
 '등',
 '따르',
 '때',
 '때문',
 '라',
 '라는',
 '로',
 '를',
 '만',
 '말',
 '며',
 '면',
 '면서',
 '명',
 '받',
 '보',
 '부터',
 '사람',
 '성',
 '수',
 '아니',
 '않',
 '어',
 '어서',
 '어야',
 '없',
 '었',
 '에',
 '에게',
 '에서',
 '와',
 '우리',
 '원',
 '월',
 '위하',
 '으로',
 '은',
 '을',
 '의',
 '이',
 '일',
 '있',
 '적',
 '제',
 '주',
 '중',
 '지',
 '지만',
 '지역',
 '통하',
 '하',
 '한',
 '화'}

In [24]:
sw.add('이다')
sw.add('하다')
sw.add('않다')
sw.add('그렇다')
sw.add('되다')
sw.add('있다')
sw.add('없다')
sw.add('싶다')

In [51]:

cleaned_token = []
for i in df["token"]:
  cleaned_token.append([ w for w in i if w not in sw])
df["token"] = cleaned_token
df

,title,contents,date,token
0,"실버일자리 새로운 시작을 꿈꾸는 법 , 은퇴 후의 보람을 찾는 방법",실버일자리란 무엇인가 실버일자리는 고령자들이 사회에 기여하고 자기 발전을 도모할 수...,2026. 2. 24. 15:46,"[실버, 일자리, 란, 무엇, 실버, 일자리, 고령자, 사회, 기여, 자기, 발전,..."
1,"은퇴 후 일자리, 나만 몰랐던 5060 실버 꿀직장 순위 BEST 4",하루 시간이면 충분해 등 하원 도우미 스마트폰만 있으면 취업 끝 데이터 수집가...,2026. 2. 20. 18:22,"[하루, 시간, 이면, 충분하다, 하원, 도우미, 스마트폰, 취업, 끝, 데이터, ..."
2,시니어 경제 편 ​ [2026] 통장에 매달 월급이? 은퇴 후 현금 부자 되는 '노...,최고의 연금 주택연금 활용하기 자식에게 집 한 채는 물려줘야지 라는 생각보다 내 ...,2026. 3. 4. 8:05,"[최고, 연금, 주택연금, 활용, 자식, 집, 채다, 물리다, 생각, 내, 노후, ..."
3,[공지] 은퇴후 보험료 폭탄 피한 비결? 노후에 장기렌트가 정답인 이유,은퇴 후 보험료 폭탄 피한 비결 노후 차량 장기렌트가 정답인 이유 은퇴 세대가 반...,2026. 2. 12. 15:44,"[은퇴, 후, 보험료, 폭탄, 피, 비결, 노후, 차량, 장기, 렌트, 정답, 이유..."
4,과거 은퇴 세대가 꿈꾸던 노후 vs 현재 은퇴 세대가 설계하는 노후,과거 은퇴 세대가 꿈꾸던 노후 현재 은퇴 세대가 설계하는 노후 과거 은퇴 세대가 ...,2025. 12. 16. 16:25,"[과거, 은퇴, 세대, 꿈꾸다, 노후, 현재, 은퇴, 세대, 설계, 노후, 과거, ..."
...,...,...,...,...
328,노인 평생교육에 대해 알아보자!,고령화의 심화와 노인 평생교육의 필요성노인 평생교육의 역할 국내 노인 평생교육 사례...,2025. 1. 1. 14:00,"[고령화, 심화, 노인, 평생교육, 필요성, 노인, 평생교육, 역할, 국내, 노인,..."
329,잘 넘어지는 사람이 치매에 걸리기 쉽다#건강체조#웃음치료#인지근력운동#건강박수#치매...,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 18. 22:05,"[해, 주신, 신, 어렵다, 힘들다, 작다, 하나, 웃다, 감사하다, 건강하다, 행..."
330,고객 생애 주기와 보험 설계 – 인생 단계별 최적의 보험 선택 가이드,고객 생애 주기와 보험 설계 고객 생애 주기와 보험 설계 인생 단계별 최적의 보험...,2025. 1. 20. 21:40,"[고객, 생애, 주기, 보험, 설계, 고객, 생애, 주기, 보험, 설계, 인생, 단..."
331,경북 영주 시니어 부업 평생 쌓아온 솜씨와 기술 활용으로 경제 활동을 독려해요,시니어의 장점만 살려 경제 활동을 독려면밀하게 검수 후 엄선된 제품 취급문의번호,2025. 1. 21. 14:00,"[시니어, 장점, 살리다, 경제, 활동, 독려, 면밀하다, 검수, 후, 엄선, 제품..."
332,#건강체조#웃음운동#치매예방체조#건강박수#자원봉사#거창사랑데이케어센터,함께 해 주신 여러신어렵고 힘들수록작은 것 하나에도웃으며 감사하면건강하고 행복해집니다,2025. 1. 10. 22:37,"[해, 주신, 신, 어렵다, 힘들다, 작다, 하나, 웃다, 감사하다, 건강하다, 행..."

In [29]:
# del df['nickName']
df

,title,contents,date,token
0,NaN,년엔 우리 회원님 들 ! 꽃길만 걸어요!우리 회원님 들!희망찬 년을 맞이하기...,2025-01-01 00:36,"[회원, 들다, 꽃길, 걸다, 회원, 들다, 희망, 찬, 맞이, 위해, 회원, 들다..."
1,NaN,첫날 피칭 둘째날 트래킹 세째날 먹방과 쉼저의 일반적 차박 방식 입니다.,2025-01-01 05:20,"[첫날, 피칭, 날, 트래킹, 날, 먹방, 쉬다, 일반, 차박, 방식]"
2,NaN,새해 아침입니다.우리 회원 님들께 더 큰 행복이 임하고 더욱 건강하시기를 기원합니다...,2025-01-01 06:51,"[새해, 아침, 회원, 님들, 크다, 행복, 임, 더욱, 건강하다, 기르다, 기원,..."
3,NaN,년 월 일 수 입니다. 새해 을사년 에는 뜻하신 모든일이 이루워지시길 기원합니다...,2025-01-01 07:04,"[새해, 을사년, 뜻, 일이, 이루다, 지다, 기원, 베트남, 붕따우, 무이네, 인..."
4,NaN,부산 청사포 일출. 새해복 많이 받으세요!,2025-01-01 08:54,"[부산, 청사포, 일출, 새해, 복, 받다]"
...,...,...,...,...
5755,NaN,점심을 버거킹으로.... 아주 오랫만에...,2026-03-04 11:46,"[점심, 버거킹, 아주]"
5756,NaN,활동이 없는건지 아님 제가 모르는 활동이 있는건가요방이 넘 조용하네요,2026-03-04 14:18,"[활동, 건지다, 아니다, 모르다, 활동, 가요, 방이, 넘다, 조용하다]"
5757,NaN,눈 오는날 올렸던매화 이제 만개했어요 하우스에서 찍은사진을배경색과 받침대를 제미나이...,2026-03-04 15:12,"[눈, 날, 올리다, 매화, 이제, 개, 하우스, 찍다, 사진, 배경, 색, 받침,..."
5758,NaN,년 월 일 모임 결산 중앙박물관 종로 모임에 참석해 주신 분들께 감사드립니...,2026-03-05 07:41,"[모임, 결산, 중앙, 박물관, 종로, 모임, 참석, 주신, 분, 감사, 드리다, ..."
5759,NaN,아름다운 인생 참 듣기 좋은 말이네요.모든 회원님들 행복한 날들 보내시기 바랍니다,2026-03-05 08:07,"[아름답다, 인생, 차다, 듣기, 좋다, 말다, 모든, 회원, 들다, 행복하다, 날..."

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5760 entries, 0 to 5759
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1608 non-null   object
 1   contents  5760 non-null   object
 2   date      5760 non-null   object
 3   token     5760 non-null   object
dtypes: object(4)
memory usage: 180.1+ KB

In [52]:
import pickle
with open('blog_retire.pkl','wb') as file:
    pickle.dump(df,file)

In [65]:
import pandas as pd
import glob
import os

# 1. Define the path where your pkl files are stored
path = 'data/'
all_files = glob.glob(os.path.join(path, "*.pkl"))

# 2. Use a list comprehension to read all files
# This is faster and more memory-efficient than appending in a loop
df_list = [pd.read_pickle(f) for f in all_files]

# 3. Concatenate everything into one DataFrame
combined_df = pd.concat(df_list, ignore_index=True)

# 4. (Optional) Check the results
print(f"Combined {len(all_files)} files.")
print(combined_df.shape)

Combined 8 files.
(35225, 4)

In [67]:
import pickle
with open('senior_all.pkl','wb') as file:
    pickle.dump(combined_df,file)

In [63]:
import pickle
with open('retire_50.pkl','wb') as file:
    pickle.dump(fifty,file)

In [66]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35225 entries, 0 to 35224
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     31073 non-null  object
 1   contents  35225 non-null  object
 2   date      32724 non-null  object
 3   token     35225 non-null  object
dtypes: object(4)
memory usage: 1.1+ MB

In [69]:
all = pd.read_pickle('senior_all.pkl')
all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35225 entries, 0 to 35224
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     31073 non-null  object
 1   contents  35225 non-null  object
 2   date      32724 non-null  object
 3   token     35225 non-null  object
dtypes: object(4)
memory usage: 1.1+ MB